config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks, :except => [:index, :show] do
      member do
        post '/toggle' => 'tasks#toggle_status', as: :toggle_status
      end
    end
  end

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :cover, CoverUploader

  has_many :tasks
  belongs_to :user
  validates :title, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title, :status, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  # Defines acceptable MIME-types
  respond_to :html, :json, :only => [:index, :show]

  # Call a function before executing a controler's method
  before_action :find_project_by_id, :only => [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
    respond_with @projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
    # @project set by filter
    @tasks = @project.tasks
  end

  def edit
    # @project set by filter
  end

  def update
    # @project set by filter

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    # @project set by filter

    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project_by_id
    @project = Project.where(:id => params[:id]).first
  end

  def project_params
    params.require(:project).permit(:title, :description, :cover)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_project_by_id, :only => [:new, :create, :destroy, :toggle_status]
  before_action :find_task_by_id, :only => [:destroy, :toggle_status]

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to project_path(@project)
  end

  def toggle_status
    @task.status = @task.status == 0 ? 1 : 0
    if @task.save
      render json: @task.to_json
    else
      render nothing: true, status: 400
    end
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end

  def find_project_by_id
    @project = Project.where(:id => params[:project_id]).first
  end

  def find_task_by_id
    @task = @project.tasks.where(:id => params[:id]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Tasky</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%- if current_user -%>
          <li><a href="#"><%= current_user.email %></a></li>
        <%- else -%>
          <li><a href="#">Not logged</a></li>
        <%- end -%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :multipart => true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.file_field :cover %>

  <%= f.submit 'Save' %>
<%- end -%>

app/views/projects/edit.html.erb
<h1>Modifica progetto</h1>

<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Lista progetti</h1>
</div>

<%- if @projects.any? -%>
  <div class="container">
    <div class="row destacados">
      <%- @projects.each do |project| -%>
        <div class="col-md-4">
          <div>
            <%= image_tag(project.cover_url, :class => 'img-circle img-thumbnail', :style => 'width: 200px; height: 200px;') %>
            <h2><%= project.title %></h2>
            <p><%= project.description %></p>
            <%= link_to 'Vedi progetto', project_path(project), :class => 'btn btn-primary' %>
            <br />
            <%= link_to 'Edit', edit_project_path(project) %> &middot;
            <%= link_to 'Delete', project_path(project), :method => :delete %>
          </div>
        </div>
      <%- end -%>
    </div>
  </div>
<%- else -%>
  <p>No projects</p>
<%- end -%>

<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h1>Nuovo progetto</h1>

<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <h1><%= @project.title %></h1>
  <p><%= @project.description %></p>
</div>

<%- if @tasks.any? -%>
  <div class="row">
    <div class="col-sm-12">
      <%- @tasks.each do |task| -%>
        <div class="input-group">
          <span class="input-group-addon">
            <input type="checkbox" class="js-toggle-task-status" data-task-id="<%= task.id %>" data-toggle-url="<%= toggle_status_project_task_path(@project, task) %>" <%= task.status == 1 ? raw(' checked') : '' %>>
          </span>
          <input type="text" class="form-control" aria-label="..." value="<%= task.title %>" disabled>
        </div><!-- /input-group -->
      <%# link_to 'Delete', project_task_path(@project, task), :method => :delete %>
      <%- end -%>
    </div>
  </ul>
<%- else -%>
  <p>No tasks for this project</p>
<%- end -%>

<%= link_to 'New task for this project', new_project_task_path(@project) %>

<%= link_to 'Back', projects_path %>

<script type="text/javascript">
  $(document).on('change', '.js-toggle-task-status', function(e) {
    $.ajax({
      url: $(this).data('toggle-url'),
      dataType: 'json',
      method: 'POST',
      success: function(xhr, status, response) {
        console.log(response)
      }
    })
  })
</script>

app/views/projects/show.json.erb
<%= raw(@project.to_json) %>

app/views/tasks/new.html.erb
<h1>Nuovo task for project <%= @project.title %></h1>
<%= form_for [@project, @task] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit 'Save' %>
<%- end -%>